ALTER TABLE users
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE professional_profile
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE student_profile
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE biometrics
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE health_record
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE medication
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE lifestyle
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE physical_training
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE financial_config
ALTER COLUMN id DROP DEFAULT;

ALTER TABLE payment
ALTER COLUMN id DROP DEFAULT;